// Curated media resources from True Friend Cambodia (CV digital ministry)
// and All Nations Church sanctuary ministry.
// Text fields are { en, km, ko, zh } pairs; use pick() from lib/i18n.

export const CHANNEL_URL = "https://www.youtube.com/@truefriendcambodia";
export const CHURCH_CHANNEL_URL = "https://www.youtube.com/@allnationschurchphnompenh";

export const VIDEOS = [
  {
    id: "QKGfNNyFu4A",
    type: "youtube",
    featured: true,
    title: {
      en: "Love Can Change Everything",
      km: "ក្តីស្រលាញ់អាចផ្លាស់ប្តូរគ្រប់យ៉ាង",
      ko: "사랑은 모든 것을 바꿀 수 있습니다",
      zh: "爱能改变一切",
    },
    subtitle: {
      en: "A short film about unconditional love and forgiveness in the midst of brokenness",
      km: "ខ្សែភាពយន្តខ្លីអំពីសេចក្តីស្រឡាញ់ឥតលក្ខខណ្ឌ និងការអត់ទោសចំកណ្តាលការបាក់បែក",
      ko: "깨어짐 속에서도 조건 없는 사랑과 용서를 전하는 단편 영화",
      zh: "一部关于在破碎中彰显无条件爱与饶恕的微电影",
    },
    description: {
      en: "When life feels beyond repair, true sacrificial love enters in. Reached over 53,000 viewers across Cambodia, pointing hearts to the redemptive grace of Jesus Christ.",
      km: "នៅពេលដែលជីវិតហាក់ដូចជាអស់សង្ឃឹម សេចក្តីស្រឡាញ់ពិតប្រាកដដែលលះបង់បានចូលមកដល់។ បានទៅដល់អ្នកទស្សនាជាង ៥៣,០០០ នាក់នៅទូទាំងប្រទេសកម្ពុជា ដោយចង្អុលបង្ហាញដួងចិត្តទៅកាន់ព្រះគុណនៃព្រះយេស៊ូវគ្រីស្ទ។",
      ko: "삶이 회복 불가능해 보일 때, 참된 희생적 사랑이 찾아옵니다. 캄보디아 전역 53,000명 이상의 시청자에게 복음의 은혜를 전했습니다.",
      zh: "当生活看似无可救药时，真正舍己的爱临到了。在柬埔寨全境触及超过5.3万名观众，引导人心归向基督的救赎恩典。",
    },
    category: "films",
    categoryLabel: {
      en: "Gospel Short Film",
      km: "ភាពយន្តខ្លីដំណឹងល្អ",
      ko: "복음 단편 영화",
      zh: "福音微电影",
    },
    duration: "6:42",
    views: "53K",
    viewsCount: 53000,
    poster: "https://i.ytimg.com/vi/QKGfNNyFu4A/maxresdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=QKGfNNyFu4A",
  },
  {
    id: "worship-service",
    type: "local",
    featured: false,
    title: {
      en: "Sunday Worship Service & Pulpit Praise",
      km: "ការថ្វាយបង្គំ និងការអធិស្ឋានថ្ងៃអាទិត្យ",
      ko: "주일 예배와 강단 찬양",
      zh: "主日崇拜与讲台赞美",
    },
    subtitle: {
      en: "Reverent congregational worship at All Nations Church sanctuary",
      km: "ការថ្វាយបង្គំដោយការគោរពកោតខ្លាចនៅក្នុងព្រះវិហារអលណេសិន",
      ko: "올네이션스교회 본당에서 드리는 경건한 회중 예배",
      zh: "万国教会主会堂庄严肃穆的会众敬拜",
    },
    description: {
      en: "Heartfelt praise, biblical preaching, and warm fellowship led by Pastor Kim Jong Ho and Leader Hun Chet in Phnom Penh.",
      km: "ការថ្វាយបង្គំ ការផ្សាយព្រះបន្ទូល និងការប្រកបគ្នាយ៉ាងកក់ក្តៅ ដឹកនាំដោយលោកគ្រូគង្វាល គីម ជុងហូ និងអ្នកដឹកនាំ ហ៊ុន ចិត្ត នៅរាជធានីភ្នំពេញ។",
      ko: "김종호 담임목사와 훈 쳇 리더가 인도하는 깊은 찬양과 말씀 선포, 따뜻한 교제.",
      zh: "由金宗浩牧师与洪哲同工带领的发自内心的赞美、圣经宣讲与温暖交通。",
    },
    category: "worship",
    categoryLabel: {
      en: "Sanctuary Worship",
      km: "ការថ្វាយបង្គំ",
      ko: "예배 실황",
      zh: "主日实况",
    },
    src: "/videos/church-intro-480p.mp4",
    poster: "/images/hero-cover.jpg",
    duration: "0:28",
    views: "Congregation",
    viewsCount: 15000,
  },
  {
    id: "yE8qZi-jeE8",
    type: "youtube",
    featured: false,
    title: {
      en: "Fighting Spiritual Darkness",
      km: "បណ្តេញវិញ្ញាណអាក្រក់ និងជ័យជម្នះក្នុងព្រះគ្រីស្ទ",
      ko: "영적 어둠과의 싸움과 승리",
      zh: "破除属灵黑暗与在基督里的得胜",
    },
    subtitle: {
      en: "Biblical truth and spiritual authority over fear and unseen oppression",
      km: "សេចក្តីពិតនៃព្រះគម្ពីរ និងអំណាចខាងវិញ្ញាណលើការភ័យខ្លាច និងការសង្កត់សង្កិន",
      ko: "두려움과 억압을 이기는 성경적 진리와 영적 권세",
      zh: "胜过恐惧与压制的圣经真理和属灵权柄",
    },
    description: {
      en: "Addressing common fears in Cambodian spiritual worldview — revealing Christ's complete authority over dark spiritual powers.",
      km: "ឆ្លើយតបទៅនឹងការភ័យខ្លាចទូទៅក្នុងទស្សនៈវិញ្ញាណរបស់ខ្មែរ — បង្ហាញពីអំណាចពេញលេញរបស់ព្រះគ្រីស្ទលើអំណាចងងឹត។",
      ko: "캄보디아 문화 속의 영적 두려움에 대해 말씀으로 답하며, 그리스도의 절대적 주권을 선포합니다.",
      zh: "直面柬埔寨文化中的属灵困惑与恐惧，显明基督统管万有与胜过黑暗的权柄。",
    },
    category: "teaching",
    categoryLabel: {
      en: "Biblical Teaching",
      km: "ការបង្រៀនព្រះគម្ពីរ",
      ko: "성경 강해",
      zh: "圣经教导",
    },
    duration: "5:18",
    views: "14K",
    viewsCount: 14000,
    poster: "https://i.ytimg.com/vi/yE8qZi-jeE8/maxresdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=yE8qZi-jeE8",
  },
  {
    id: "b9OI_jdd3ro",
    type: "youtube",
    featured: false,
    title: {
      en: "Unwanted — Value in God's Eyes",
      km: "អ្វីដែលអ្នកមិនចង់បាន — តម្លៃក្នុងព្រះនេត្រនៃព្រះ",
      ko: "버림받은 마음 — 하나님의 눈에 비친 가치",
      zh: "不被接纳的生命 —— 神眼中的珍贵价值",
    },
    subtitle: {
      en: "Finding identity when feeling rejected and abandoned by the world",
      km: "ការស្វែងរកអត្តសញ្ញាណពិត នៅពេលមានអារម្មណ៍ថាត្រូវគេបោះបង់ចោល",
      ko: "세상에서 거절당했을 때 발견하는 참된 정체성",
      zh: "在被拒绝与孤立时寻得真正的身份认同",
    },
    description: {
      en: "A compelling story for youth struggling with self-worth, peer rejection, and familial pressure, introducing the Heavenly Father who never forsakes.",
      km: "រឿងដ៏មានអត្ថន័យសម្រាប់យុវជនដែលតស៊ូជាមួយតម្លៃផ្ទាល់ខ្លួន ការបដិសេធ និងសម្ពាធគ្រួសារ ដោយណែនាំពីព្រះវរបិតាដែលមិនដែលបោះបង់យើងឡើយ។",
      ko: "자존감과 거절감으로 아파하는 청년들을 위한 드라마, 결코 떠나지 않으시는 하늘 아버지를 소개합니다.",
      zh: "专为挣扎于自我价值与被拒绝感的青年编创的微电影，引向永不离弃的天父。",
    },
    category: "films",
    categoryLabel: {
      en: "Gospel Short Film",
      km: "ភាពយន្តខ្លីដំណឹងល្អ",
      ko: "복음 단편 영화",
      zh: "福音微电影",
    },
    duration: "4:55",
    views: "9.7K",
    viewsCount: 9700,
    poster: "https://i.ytimg.com/vi/b9OI_jdd3ro/maxresdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=b9OI_jdd3ro",
  },
  {
    id: "K_QZE8S-uic",
    type: "youtube",
    featured: false,
    title: {
      en: "Words That Hurt — The Power to Heal",
      km: "ពាក្យសម្តីឈឺចាប់ — អំណាចនៃការប្រោសឱ្យជា",
      ko: "상처 주는 말 — 치유의 능력",
      zh: "伤人的言语 —— 医治与释放的大能",
    },
    subtitle: {
      en: "How spoken wounds affect the heart and the healing balm of Christ",
      km: "របៀបដែលពាក្យសម្តីធ្វើឱ្យប៉ះពាល់ដល់ចិត្ត និងការព្យាបាលតាមរយៈព្រះគ្រីស្ទ",
      ko: "말의 상처와 그리스도 안에서 누리는 참된 회복",
      zh: "言语带来的隐秘创伤以及基督里的医治之道",
    },
    description: {
      en: "Explores the psychological and spiritual toll of verbal cruelty, showing how biblical forgiveness and Christ's affirmation break generational cycles.",
      km: "ស្វែងយល់ពីផលប៉ះពាល់ផ្លូវចិត្ត និងផ្លូវវិញ្ញាណនៃពាក្យសម្តីអាក្រក់ ដោយបង្ហាញពីរបៀបដែលការអភ័យទោសតាមព្រះគម្ពីរអាចបំបែកភាពឈឺចាប់បាន។",
      ko: "언어 폭력의 깊은 상처를 직시하고, 성경적 용서와 사랑으로 대물림되는 아픔을 끊어냅니다.",
      zh: "探讨言语暴力的创伤，见证基于圣经的饶恕如何带来真正的和好与释放。",
    },
    category: "films",
    categoryLabel: {
      en: "Gospel Short Film",
      km: "ភាពយន្តខ្លីដំណឹងល្អ",
      ko: "복음 단편 영화",
      zh: "福音微电影",
    },
    duration: "5:30",
    views: "6.2K",
    viewsCount: 6200,
    poster: "https://i.ytimg.com/vi/K_QZE8S-uic/maxresdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=K_QZE8S-uic",
  },
  {
    id: "campus-tour",
    type: "local",
    featured: false,
    title: {
      en: "Church Campus & Grounds Aerial Tour",
      km: "ទិដ្ឋភាពទូទៅនៃបរិវេណព្រះវិហារ និងវិទ្យាស្ថាន",
      ko: "교회 부지 및 캠퍼스 둘러보기",
      zh: "教会园区与神学院航拍全景",
    },
    subtitle: {
      en: "Campus grounds, sanctuary, fellowship hall and prayer gardens",
      km: "បរិវេណព្រះវិហារ សាលប្រកបគ្នា និងសួនអធិស្ឋាន",
      ko: "본당 예배당, 친교실 및 기도 동산 전경",
      zh: "大礼拜堂、团契大厅与祷告花园巡礼",
    },
    description: {
      en: "A birds-eye view of All Nations Church campus facilities dedicated to gospel proclamation, youth education, and theological discipleship in Cambodia.",
      km: "ទិដ្ឋភាពពីលើអាកាសនៃបរិវេណព្រះវិហារអលណេសិន សម្រាប់កិច្ចការផ្សាយដំណឹងល្អ ការអប់រំយុវជន និងការបណ្តុះសិស្សទេវវិទ្យានៅកម្ពុជា។",
      ko: "캄보디아의 다음 세대 교육과 복음 전파를 위해 헌신된 올네이션스교회 캠퍼스 둘러보기.",
      zh: "万国教会致力于在柬埔寨宣扬福音、培养青年与神学门徒的园区风貌。",
    },
    category: "worship",
    categoryLabel: {
      en: "Campus & Sanctuary",
      km: "បរិវេណព្រះវិហារ",
      ko: "캠퍼스 안내",
      zh: "园区概览",
    },
    src: "/videos/church-campus.mp4",
    poster: "/images/church-campus-poster.jpg",
    duration: "0:18",
    views: "Campus",
    viewsCount: 8000,
  },
  {
    id: "8PE-ijDQZcE",
    type: "youtube",
    featured: false,
    title: {
      en: "The Apple — Salvation Given Freely",
      km: "ផ្លែប៉ោម — សេចក្តីសង្គ្រោះដែលបានប្រទានដោយឥតគិតថ្លៃ",
      ko: "사과 — 값없이 주어지는 구원의 은혜",
      zh: "苹果 —— 白白赐下的救恩",
    },
    subtitle: {
      en: "An illustrated parable of grace, debt, and the cross of Christ",
      km: "រឿងប្រៀបប្រដូចអំពីព្រះគុណ បំណុលបាប និងឈើឆ្កាងនៃព្រះគ្រីស្ទ",
      ko: "은혜와 죗값, 그리고 십자가를 명쾌하게 설명하는 비유",
      zh: "关于恩典、罪债与基督十架的生动比喻",
    },
    description: {
      en: "Explaining the doctrine of substitutionary atonement in clear, everyday terms accessible to every generation of Cambodian seekers.",
      km: "ការពន្យល់អំពីគោលលទ្ធិនៃសេចក្តីសង្គ្រោះជំនួស ក្នុងពាក្យពេចន៍ងាយយល់ និងជាក់ស្តែងសម្រាប់អ្នកស្វែងរកសេចក្តីពិតគ្រប់ជំនាន់។",
      ko: "대속의 은혜와 복음의 정수를 모든 세대가 쉽게 이해할 수 있도록 일상의 언어로 풀어냅니다.",
      zh: "用平易近人、清晰深刻的日常语言阐述替代性救赎的纯正神学核心。",
    },
    category: "teaching",
    categoryLabel: {
      en: "Biblical Teaching",
      km: "ការបង្រៀនព្រះគម្ពីរ",
      ko: "성경 강해",
      zh: "圣经教导",
    },
    duration: "4:12",
    views: "3.2K",
    viewsCount: 3200,
    poster: "https://i.ytimg.com/vi/8PE-ijDQZcE/maxresdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=8PE-ijDQZcE",
  },
  {
    id: "ina9O-Rp0Vc",
    type: "youtube",
    featured: false,
    title: {
      en: "When Sweet Love Turns Bitter",
      km: "ក្តីស្រលាញ់ផ្អែមល្ហែមបានតែដំបូង",
      ko: "달콤했던 사랑이 쓴맛으로 변할 때",
      zh: "当甜蜜的爱变质成苦涩",
    },
    subtitle: {
      en: "Navigating relationship disillusionment and finding unchanging love",
      km: "ការឆ្លងកាត់ការខកចិត្តក្នុងទំនាក់ទំនង និងការស្វែងរកសេចក្តីស្រឡាញ់ពិត",
      ko: "관계의 환멸을 넘어 영원히 변치 않는 사랑을 발견하기",
      zh: "穿越情感幻灭，寻找永不改变的真爱",
    },
    description: {
      en: "An honest short film on romantic heartache and how worldly romance cannot bear the weight of ultimate human longing.",
      km: "ខ្សែភាពយន្តខ្លីដ៏ស្មោះត្រង់អំពីការឈឺចាប់ក្នុងរឿងស្នេហា និងរបៀបដែលស្នេហាលោកីយ៍មិនអាចបំពេញបំណងប្រាថ្នាពិតនៃដួងចិត្តបាន។",
      ko: "인간적인 사랑의 한계와 상처를 솔직하게 나누며, 사람의 영혼을 채우는 하나님의 사랑을 조명합니다.",
      zh: "诚恳探讨恋爱中的心碎与落空，阐明唯有基督永恒之爱才能真正填补人心的渴求。",
    },
    category: "films",
    categoryLabel: {
      en: "Gospel Short Film",
      km: "ភាពយន្តខ្លីដំណឹងល្អ",
      ko: "복음 단편 영화",
      zh: "福音微电影",
    },
    duration: "5:08",
    views: "2.2K",
    viewsCount: 2200,
    poster: "https://i.ytimg.com/vi/ina9O-Rp0Vc/maxresdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=ina9O-Rp0Vc",
  },
  {
    id: "fpGqOFFvFhs",
    type: "youtube",
    featured: false,
    title: {
      en: "Does God Really Exist?",
      km: "តើមានព្រះដែរឬទេ? ការស្វែងរកសេចក្តីពិត",
      ko: "하나님은 정말 계실까요? 진리를 향한 질문",
      zh: "神真的存在吗？探寻生命真理",
    },
    subtitle: {
      en: "Reasonable evidence, creation design, and moral longing for the Creator",
      km: "ភស្តុតាងសមហេតុផល ការបង្កើត និងសេចក្តីស្រេកឃ្លាននៃចិត្តចំពោះព្រះអាទិករ",
      ko: "창조 세계와 양심이 증언하는 창조주 하나님에 대한 변증",
      zh: "从宇宙造化与道德渴望论证创造主的真实存在",
    },
    description: {
      en: "Engaging philosophical skepticism and scientific curiosity with biblical humility, answering youth questions on the reality of God.",
      km: "ការឆ្លើយតបទៅនឹងការសង្ស័យ និងសំណួរវិទ្យាសាស្ត្រ ដោយការបន្ទាបខ្លួនតាមព្រះគម្ពីរ អំពីវត្តមានពិតប្រាកដរបស់ព្រះ។",
      ko: "회의주의와 과학적 질문 앞에 성경의 진리를 조리 있고 겸손하게 증거합니다.",
      zh: "以理性与敬畏的心回应青年人对于无神论与科学怀疑论的深层追问。",
    },
    category: "questions",
    categoryLabel: {
      en: "Life Questions & Apologetics",
      km: "សំណួរជីវិត និងជំនឿ",
      ko: "기독교 변증",
      zh: "信仰问答与护教",
    },
    duration: "4:40",
    views: "1K",
    viewsCount: 1000,
    poster: "https://i.ytimg.com/vi/fpGqOFFvFhs/maxresdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=fpGqOFFvFhs",
  },
  {
    id: "f0v5U7FlS7E",
    type: "youtube",
    featured: false,
    title: {
      en: "Freedom Is the True Beauty of Life",
      km: "សេរីភាពជាភាពស្រស់ស្អាតនៃជីវិតដ៏ពិត",
      ko: "자유 — 참된 삶의 아름다움",
      zh: "真自由是生命中最美好的恩典",
    },
    subtitle: {
      en: "Breaking free from guilt, shame, and past bondages through the Son of God",
      km: "ការរួចផុតពីកំហុស ភាពអាម៉ាស់ និងចំណងអតីតកាល តាមរយៈព្រះរាជបុត្រានៃព្រះ",
      ko: "죄와 수치심, 과거의 결박에서 벗어나 누리는 참된 해방",
      zh: "脱离罪疚、羞耻与过往锁链的真实释放",
    },
    description: {
      en: "'If the Son sets you free, you will be free indeed.' A message of gospel liberation for anyone weighed down by guilt or past regret.",
      km: "«ប្រសិនបើតំណាងព្រះរាជបុត្រាដោះលែងអ្នក នោះអ្នកនឹងបានរួចខ្លួនយ៉ាងពិតប្រាកដ។» សារដំណឹងល្អនៃការរំដោះសម្រាប់អ្នកដែលផ្ទុកបន្ទុកធ្ងន់។",
      ko: "'아들이 너희를 자유롭게 하면 너희가 참으로 자유하리라.' 죄책감과 억압에 짓눌린 이들에게 전하는 복음의 해방 선언.",
      zh: "“天父的儿子若叫你们自由，你们就真自由了。” 宣告十架救赎带来的全然释放与新生。",
    },
    category: "teaching",
    categoryLabel: {
      en: "Biblical Teaching",
      km: "ការបង្រៀនព្រះគម្ពីរ",
      ko: "성경 강해",
      zh: "圣经教导",
    },
    duration: "3:55",
    views: "716",
    viewsCount: 716,
    poster: "https://i.ytimg.com/vi/f0v5U7FlS7E/maxresdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=f0v5U7FlS7E",
  },
  {
    id: "9bTPJS_s3tQ",
    type: "youtube",
    featured: false,
    title: {
      en: "Why Am I Poor? Finding True Wealth",
      km: "ហេតុអ្វីខ្ញុំក្រ? ការស្វែងរកទ្រព្យសម្បត្តិពិត",
      ko: "왜 나는 가난할까? 참된 부를 찾아서",
      zh: "我为什么贫穷？寻见永恒真实的财富",
    },
    subtitle: {
      en: "Hope beyond financial hardship and the enduring riches of the Kingdom",
      km: "សេចក្តីសង្ឃឹមលើសពីការលំបាកខាងសម្ភារៈ និងទ្រព្យសម្បត្តិដ៏ស្ថិតស្ថេរនៃនគរព្រះ",
      ko: "물질적 결핍을 넘어 하나님 나라의 영원한 부요함을 바라보기",
      zh: "跨越物质匮乏的藩篱，注目天国永不衰残的基业",
    },
    description: {
      en: "Confronting poverty with compassion, countering prosperity myths, and showing how God lifts up the humble and enriches the soul.",
      km: "ការប្រឈមមុខនឹងភាពក្រីក្រដោយក្តីមេត្តាករុណា និងការបង្ហាញពីរបៀបដែលព្រះលើកតម្កើងអ្នកដែលបន្ទាបខ្លួន និងបំពេញចិត្តខាងវិញ្ញាណ។",
      ko: "가난의 고통을 함께 나누며 기복 신앙을 넘어, 겸손한 자를 높이시고 영혼을 부요케 하시는 하나님을 증거합니다.",
      zh: "以爱心体恤贫困者的辛酸，破除成功神学虚妄，显明神赐给谦卑人的永恒属灵丰富。",
    },
    category: "questions",
    categoryLabel: {
      en: "Life Questions & Apologetics",
      km: "សំណួរជីវិត និងជំនឿ",
      ko: "기독교 변증",
      zh: "信仰问答与护教",
    },
    duration: "4:32",
    views: "489",
    viewsCount: 489,
    poster: "https://i.ytimg.com/vi/9bTPJS_s3tQ/maxresdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=9bTPJS_s3tQ",
  },
  {
    id: "8wuuc6P_-XQ",
    type: "youtube",
    featured: false,
    title: {
      en: "I'm Tired of Everything — Come and Rest",
      km: "ខ្ញុំហត់នឿយហើយ — ចូលមកទទួលការសម្រាក",
      ko: "모든 것에 지쳐버렸을 때 — 내게로 오라",
      zh: "我感到疲惫不堪 —— 来到主前得安息",
    },
    subtitle: {
      en: "A pastoral refuge for heavy hearts, anxiety, and silent exhaustion",
      km: "ជម្រកខាងវិញ្ញាណសម្រាប់ចិត្តដែលធ្ងន់ ការថប់បារម្ភ និងភាពហត់នឿយស្ងប់ស្ងាត់",
      ko: "무거운 짐과 불안, 지친 마음을 어루만지시는 주님의 쉼",
      zh: "为焦虑、重压与隐秘疲惫的人预备的避风港",
    },
    description: {
      en: "Jesus said: 'Come to me, all you who are weary and burdened, and I will give you rest.' A quiet companion for difficult nights.",
      km: "ព្រះយេស៊ូវមានព្រះបន្ទូលថា៖ «អស់អ្នកដែលនឿយព្រួយ ហើយផ្ទុកបន្ទុកធ្ងន់អើយ ចូរមកឯខ្ញុំ ខ្ញុំនឹងឱ្យអ្នករាល់គ្នាបានសម្រាក។»",
      ko: "'수고하고 무거운 짐 진 자들아 다 내게로 오라 내가 너희를 쉬게 하리라.' 삶의 어두운 밤을 지나는 이들을 위한 위로의 메시지.",
      zh: "“凡劳苦担重担的人，可以到我这里来，我就使你们得安息。” 为身处夜深人静、心力交瘁者带来的恩言。",
    },
    category: "questions",
    categoryLabel: {
      en: "Life Questions & Apologetics",
      km: "សំណួរជីវិត និងជំនឿ",
      ko: "기독교 변증",
      zh: "信仰问答与护教",
    },
    duration: "4:15",
    views: "335",
    viewsCount: 335,
    poster: "https://i.ytimg.com/vi/8wuuc6P_-XQ/maxresdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=8wuuc6P_-XQ",
  },
];
